legend = ["LAT_ACCEL_FACTOR", "MAX_LAT_ACCEL_MEASURED", "FRICTION"]
### angle control
# Nissan appears to have torque
"XTRAIL" = [nan, 1.5, nan]
"ALTIMA" = [nan, 1.5, nan]
"LEAF_IC" = [nan, 1.5, nan]
"LEAF" = [nan, 1.5, nan]
"ROGUE" = [nan, 1.5, nan]

# New subarus angle based controllers
"FORESTER_2022" = [nan, 3.0, nan]
"OUTBACK_2023" = [nan, 3.0, nan]
"ASCENT_2023" = [nan, 3.0, nan]

# Toyota LTA also has torque
"RAV4_TSS2_2023" = [nan, 3.0, nan]

# Tesla has high torque
"AP1_MODELS" = [nan, 2.5, nan]
"AP2_MODELS" = [nan, 2.5, nan]
"MODELS_RAVEN" = [nan, 2.5, nan]

# Guess
"BRONCO_SPORT_MK1" = [nan, 1.5, nan]
"ESCAPE_MK4" = [nan, 1.5, nan]
"EXPLORER_MK6" = [nan, 1.5, nan]
"F_150_MK14" = [nan, 1.5, nan]
"FOCUS_MK4" = [nan, 1.5, nan]
"MAVERICK_MK1" = [nan, 1.5, nan]
"F_150_LIGHTNING_MK1" = [nan, 1.5, nan]
"MUSTANG_MACH_E_MK1" = [nan, 1.5, nan]
###

# No steering wheel
"BODY" = [nan, 1000, nan]

# Totally new cars
"RAM_1500_5TH_GEN" = [2.0, 2.0, 0.05]
"RAM_HD_5TH_GEN" = [1.4, 1.4, 0.05]
"OUTBACK" = [2.0, 2.0, 0.2]
"ESCALADE" = [1.899999976158142, 1.842270016670227, 0.1120000034570694]
"ESCALADE_ESV_2019" = [1.15, 1.3, 0.2]
"BOLT_EUV" = [2.0, 2.0, 0.05]
"SILVERADO" = [1.9, 1.9, 0.112]
"TRAILBLAZER" = [1.33, 1.9, 0.16]
"EQUINOX" = [2.5, 2.5, 0.05]
"CADDY_MK3" = [1.2, 1.2, 0.1]
"PASSAT_NMS" = [2.5, 2.5, 0.1]
"SHARAN_MK2" = [2.5, 2.5, 0.1]
"ACADIA" = [1.6, 1.6, 0.2]
"LEXUS_IS_TSS2" = [2.0, 2.0, 0.1]
"LEXUS_GS_F" = [2.5, 2.5, 0.08]

# Dashcam or fallback configured as ideal car
"MOCK" = [10.0, 10, 0.0]

# Manually checked
"CIVIC_2022" = [2.5, 1.2, 0.15]
"HRV_3G" = [2.5, 1.2, 0.2]
